---
title: "M11 Exercise"
output:
  word_document: default
  html_document: default
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## M11 Exercises

```{r}
library(tidyverse)
```

```{r}
scores <- 
  tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
```

```{r}
scores
```

```{r}
scores%>%
  slice(1:3)
first_three<-scores%>%
  slice(1:3)
```
```{r}
scores%>%
  arrange(desc(math_score))

#Bobby and Alice tied with a score of 5
```
```{r}
scores%>%
  arrange(name)
```
```{r}
scores%>%
  arrange(sex)
```
```{r}
scores%>%
  arrange(school, teacher, sex, math_score, reading_score)
```
```{r}
scores%>%
  select(name, math_score, reading_score)

scores%>%
  select(-sex)

scores%>%
  select(-math_score, -reading_score)

scores%>%
  select(sex, everything())
```


```{r}
scores%>%
  filter(sex == "male" & school == "south")

scores%>%
  filter(math_score > mean(math_score))

scores%>%
  filter(math_score>=4 , reading_score>=3)

scores%>%
  filter(math_score<=3 | reading_score<=3)

scores%>%
  filter(reading_score %in% 2:4)

scores%>%
  filter(substr(name, 1,1) == 'm')

scores%>%
  group_by(teacher)%>%
  filter(max(math_score) == 5)

scores%>%
  group_by(sex)%>%
  filter(mean(math_score)==4)
```
```{r}
scores%>%
  mutate(math_score_ten = math_score*10, reading_score_ten = reading_score*10)

scores%>%
  mutate(math_read_avg = (math_score+reading_score)/2)

```
```{r}
scores%>%
  group_by(sex)%>%
  mutate(math_score_centered_by_sex = math_score - mean(math_score))%>%
  arrange(desc(math_score_centered_by_sex))

scores%>%
  group_by(teacher)%>%
  mutate(reading_score_centered_by_teacher = math_score - mean(math_score))
```
```{r}
scores%>%
  group_by(school)%>%
  summarize(min_math_score = min(math_score))

scores%>%
  group_by(teacher)%>%
  summarize(max_math_score = max(math_score))
```

